---
# tasks file for ansible-role-nfs_mount/
- name: Fail if nfs_mount is defined
  fail: 
     msg: "nfs_mount is no longer supported. Change configuration to nfs_mounts instead"
  when: nfs_mount is defined

- name: Create directories (if they do not exist) from nfs_mounts
  file:
     path: "{{ item.name }}"
     state: directory
     mode: "{{ item.dirmode | default ('0755') }}"
     group: "{{ item.group | default(omit) }}"
     owner: "{{ item.owner | default(omit) }}"
     attributes: "{{ item.attributes | default(omit) }}"
  with_items: "{{ nfs_mounts }}"
  when:
    - nfs_mounts is defined
    - item.name is defined

- name: add mountpoints from nfs_mounts
  mount:
        fstype: "{{ item.fstype | default('nfs') }}"
        name: "{{ item.name }}"
        src: "{{ item.src }}"
        state: "{{ item.state | default('mounted') }}"
        opts: "{{ item.opts | default('defaults') }}"
  with_items: "{{ nfs_mounts }}"
  when:
    - nfs_mounts is defined
    - item.name is defined
    - item.src is defined
